name: 'Get changelog diff'
description: 'get the changelog message form x last version as output'
inputs:
  lastVersion:  # id of input
    description: 'Version from whre you want the diff'
    required: true
    default: 'latest'
  changelogPath:
    description: 'Path of your changelog file'
    required: true
    default: 'CHANGELOG.md'
outputs:
  cnages: # output will be available to future steps
    description: 'The changes from lastVersion in markdown format'
runs:
  using: 'node12'
  main: 'dist/index.js'
